const Dataset = {
  division: [
    {
      name: "Barishal",
      district: [
        {
          name: "Barguna",
          upazila: [
            "Amtali",
            "Bamna",
            "Barguna-S",
            "Betagi",
            "Patharghata",
            "Taltali",
          ],
        },
        {
          name: "Barishal",
          upazila: [
            "Agailjhara",
            "Babuganj",
            "Bakerganj",
            "Banaripara",
            "Barishal-S",
            "Gouranadi",
            "Hizla",
            "Mehendiganj",
            "Muladi",
            "Uzirpur",
          ],
        },
        {
          name: "Bhola",
          upazila: [
            "Bhola-S",
            "Borhanuddin",
            "Charfassion",
            "Daulatkhan",
            "Lalmohan",
            "Monpura",
            "Tazumuddin",
          ],
        },
        {
          name: "Jhalokathi",
          upazila: ["Jhalokathi-S", "Kathalia", "Nalchity", "Rajapur"],
        },
        {
          name: "Pirojpur",
          upazila: [
            "Bhandaria",
            "Kawkhali",
            "Mothbaria",
            "Nazirpur",
            "Nesarabad",
            "Pirojpur-S",
            "Zianagar",
          ],
        },

        {
          name: "Patuakhali",
          upazila: [
            "Bauphal",
            "Dashmina",
            "Dumki",
            "Galachipa",
            "Kalapara",
            "Mirjaganj",
            "Patuakhali",
            "Rangabali",
          ],
        },
      ],
    },
    {
      name: "Chattogram",
      district: [
        {
          name: "B.baria",
          upazila: [
            "Akhaura",
            "Ashuganj",
            "B.Baria-S",
            "Bancharampur",
            "Bijoynagar",
            "Kasba",
            "Nabinagar",
            "Nasirnagar",
            "Sarail",
          ],
        },
        {
          name: "Bandarban",
          upazila: [
            "Alikadam",
            "Bandarban-S",
            "Lama",
            "Naikhyongchari",
            "Rowangchari",
            "Ruma",
            "Thanchi",
          ],
        },
        {
          name: "Chandpur",
          upazila: [
            "Chandpur-S",
            "Faridganj",
            "Haimchar",
            "Haziganj",
            "Kachua",
            "Matlab (Dakshin)",
            "Matlab (Uttar)",
            "Shahrasti",
          ],
        },
        {
          name: "Chattogram",
          upazila: [
            "Anwara",
            "Banskhali",
            "Boalkhali",
            "Chandanish",
            "Fatikchari",
            "Hathazari",
            "Karnaphuli",
            "Lohagara",
            "Mirsharai",
            "Patiya",
            "Rangunia",
            "Raojan",
            "Sandwip",
            "Satkania",
            "Sitakunda",
          ],
        },
        {
          name: "CoxsBazar",
          upazila: [
            "Coxsbazar-S",
            "Kutubdia",
            "Chakoria",
            "Moheskali",
            "Pekua",
            "Ramu",
            "Teknaf",
            "Ukhia",
          ],
        },
        {
          name: "Cumilla",
          upazila: [
            "Barura",
            "Brahmanpara",
            "Burichong",
            "Chandina",
            "Chouddogram",
            "Cumilla-s",
            "Cumilla-s Daksin",
            "Daudkhandi",
            "Debidwar",
            "Homna",
            "Laksham",
            "Lalmai",
            "Meghna",
            "Monuhorgonj",
            "Muradnagar",
            "Nangalkot",
            "Titas",
          ],
        },
        {
          name: "Feni",
          upazila: [
            "Chhagalniya",
            "Daganbhuiyan",
            "Feni-s",
            "Fulgazi",
            "Porshuram",
            "Sonagazi",
          ],
        },
        {
          name: "Khagrachari",
          upazila: [
            "Dighinala",
            "Guimara",
            "Khagrachari-S",
            "Laxmichari",
            "Mahalchari",
            "Manikchari",
            "Matiranga",
            "Panchari",
            "Ramgarh",
          ],
        },
        {
          name: "Laxmipur",
          upazila: ["Komol Nagar", "Laxmipur-S", "Raipur", "Raipur", "Raipur"],
        },
        {
          name: "Noakhali",
          upazila: [
            "Begumgan",
            "Chatkhil",
            "Companiganj",
            "Hatiya",
            "Kabir Hat",
            "Noakhali-S",
            "Senbag",
            "Subarna Char",
            "Sonaimuri",
          ],
        },
        {
          name: "Rangamati",
          upazila: [
            "Baghaichari",
            "Barkal",
            "Belaichari",
            "Juraichari",
            "Kaptai",
            "Kaukhali",
            "Langadu",
            "Nanniarchar",
            "Rajosthali",
            "Rangamati-S",
          ],
        },
      ],
    },
    {
      name: "Dhaka",
      district: [
        {
          name: "Dhaka",
          upazila: ["Dhamrai", "Dohar", "Keraniganj", "Nawabganj", "Savar"],
        },
        {
          name: "Faridpur",
          upazila: [
            "Alfadanga",
            "Bhanga",
            "Boalmari",
            "Charbhadrasan",
            "Faridpur-S",
            "Madhukhali",
            "Nagarkanda",
            "Sadarpur",
            "Saltha",
          ],
        },
        {
          name: "Gazipur",
          upazila: ["Gazipur-S", "Kaliakoir", "Kaliganj", "Kapasia", "Sreepur"],
        },
        {
          name: "Gopalganj",
          upazila: [
            "Gopalganj-S",
            "Kasiani",
            "Kotwalipara",
            "Muksudpur",
            "Tungipara",
          ],
        },
        {
          name: "Kishoreganj",
          upazila: [
            "Austagram",
            "Bajitpur",
            "Bhairab",
            "Hossainpur",
            "Itna",
            "Karimganj",
            "Katiadi",
            "Kishoreganj-S",
            "Kuliarchar",
            "Mithamoin",
            "Nikli",
            "Pakundia",
            "Tarail",
          ],
        },
        {
          name: "Madaripur",
          upazila: ["Kalkini", "Madaripur-S", "Rajoir", "Shibchar"],
        },
        {
          name: "Manikganj",
          upazila: [
            "Daulatpur",
            "Ghior",
            "Harirampur",
            "Manikganj-S",
            "Saturia",
            "Shivalaya",
            "Singair",
          ],
        },
        {
          name: "Narayanganj",
          upazila: [
            "Araihazar",
            "Bandar",
            "Narayanganj-S",
            "Rupganj",
            "Sonargaon",
          ],
        },
        {
          name: "Munshiganj",
          upazila: [
            "Gazaria",
            "Lauhajong",
            "Munshiganj-S",
            "Sirajdikhan",
            "Sreenagar",
            "Tongibari",
          ],
        },
        {
          name: "Narshingdi",
          upazila: [
            "Belabo",
            "Monohardi",
            "Narshingdi-S",
            "Palash",
            "Raipura",
            "Shibpur",
          ],
        },
        {
          name: "Rajbari",
          upazila: [
            "Baliakandi",
            "Goalanda",
            "Kalukhali",
            "Pangsha",
            "Rajbari-S",
          ],
        },
        {
          name: "Shariatpur",
          upazila: [
            "Bhedarganj",
            "Damuddya",
            "Goshairhat",
            "Janjira",
            "Naria",
            "Shariatpur-S",
          ],
        },
        {
          name: "Tangail",
          upazila: [
            "Basail",
            "Bhuapur",
            "DelduarDelduar",
            "Dhanbari",
            "Ghatail",
            "Gopalpur",
            "Kalihati",
            "Madhupur",
            "Mirzapur",
            "Nagarpur",
            "Shakhipur",
            "Tangail-S",
          ],
        },
      ],
    },
    {
      name: "Khulna",
      district: [
        {
          name: "Jhenaidah",
          upazila: [
            "Harinakunda",
            "Jhenaidah-S",
            "Kaliganj",
            "Kotchandpur",
            "Moheshpur",
            "Shailkupa",
          ],
        },
        {
          name: "Khulna",
          upazila: [
            "Batiaghata",
            "Dacope",
            "Dighalia",
            "Dumuria",
            "Koira",
            "Paikgacha",
            "Phultala",
            "Rupsa",
            "Terokhada",
          ],
        },
        {
          name: "Kushtia",
          upazila: [
            "Bheramara",
            "Daulatpur",
            "Khoksha",
            "Kumarkhali",
            "Kushtia-S",
            "Mirpur",
          ],
        },
        {
          name: "Magura",
          upazila: ["Magura-S", "Mohammadpur", "Salikha", "Sreepur"],
        },
        {
          name: "Meherpur",
          upazila: ["Meherpur-S", "Mujib Nagar", "Gangni"],
        },
        {
          name: "Narail",
          upazila: ["Kalia", "Lohagara", "Narail-S"],
        },
        {
          name: "Satkhira",
          upazila: [
            "Assasuni",
            "Debhata",
            "Kalaroa",
            "Kaliganj",
            "Satkhira-S",
            "Shyamnagar",
            "Tala",
          ],
        },
      ],
    },
    {
      name: "Mymensingh",
      district: [
        {
          name: "Jamalpur",
          upazila: [
            "Bakshiganj",
            "Dewanganj",
            "Islampur",
            "Jamalpur-S",
            "Madarganj",
            "Melendah",
            "Sarishabari",
          ],
        },
        {
          name: "Mymensingh",
          upazila: [
            "Bhaluka",
            "Dhobaura",
            "Fulbaria",
            "Gaffargaon",
            "Gouripur",
            "Haluaghat",
            "Ishwarganj",
            "Muktagacha",
            "Mymensingh-S",
            "Nandail",
            "Phulpur",
            "Trishal",
            "Tarakanda",
          ],
        },
        {
          name: "Netrakona",
          upazila: [
            "Atpara",
            "Barhatta",
            "Durgapur",
            "Kalmakanda",
            "Kendua",
            "Khaliajuri",
            "Madan",
            "Mohanganj",
            "Netrakona-S",
            "Purbadhala",
          ],
        },
        {
          name: "Sherpur",
          upazila: [
            "Jhenaigati",
            "Nakla",
            "Nalitabari",
            "Sherpur-S",
            "Sreebordi",
          ],
        },
      ],
    },
    {
      name: "Rajshahi",
      district: [
        {
          name: "Bogura",
          upazila: [
            "Adamdighi",
            "Bogura-S",
            "Dhunot",
            "Dhupchancia",
            "Gabtali",
            "Kahaloo",
            "Nandigram",
            "Sariakandi",
            "Shajahanpur",
            "Sherpur",
            "Shibganj",
            "Sonatala",
          ],
        },
        {
          name: "C-Nawabganj",
          upazila: [
            "Bholahat",
            "Gomostapur",
            "Nachol",
            "Nawabganj-S",
            "Shibganj",
          ],
        },
        {
          name: "Joypurhat",
          upazila: ["Akkelpur", "Joypurhat-S", "Kalai", "Khetlal", "Panchbibi"],
        },
        {
          name: "Naogaon",
          upazila: [
            "Atrai",
            "Badalgachi",
            "Dhamoirhat",
            "Manda",
            "Mohadevpur",
            "Naogaon-S",
            "Niamatpur",
            "Patnitala",
            "Porsha",
            "Raninagar",
            "Shapahar",
          ],
        },
        {
          name: "Natore",
          upazila: [
            "Bagatipara",
            "Baraigram",
            "Gurudaspur",
            "Lalpur",
            "Naldanga",
            "Natore-S",
            "Singra",
          ],
        },
        {
          name: "Pabna",
          upazila: [
            "Atghoria",
            "Bera",
            "Bhangura",
            "Chatmohar",
            "Faridpur",
            "Ishwardi",
            "Pabna-S",
            "Santhia",
          ],
        },
        {
          name: "Rajshahi",
          upazila: [
            "Bagha",
            "Bagmara",
            "Charghat",
            "Durgapur",
            "Godagari",
            "Mohanpur",
            "Paba",
            "Puthia",
            "Tanore",
          ],
        },
        {
          name: "Sirajganj",
          upazila: [
            "Belkuchi",
            "Chowhali",
            "Kamarkhand",
            "Kazipur",
            "Raiganj",
            "Shahzadpur",
            "Sirajganj-S",
            "Tarash",
            "Ullapara",
          ],
        },
      ],
    },
    {
      name: "Rangpur",
      district: [
        {
          name: "Dinajpur",
          upazila: [
            "Birampur",
            "Birganj",
            "Birol",
            "Bochaganj",
            "Chirirbandar",
            "Dinajpur-S",
            "Fulbari",
            "Ghoraghat",
            "Hakimpur",
            "Kaharol",
            "Khanshama",
          ],
        },
        {
          name: "Gaibandha",
          upazila: [
            "Fulchari",
            "Gaibandha-S",
            "Gobindaganj",
            "Palashbari",
            "Sadullapur",
            "Saghata",
            "Sundarganj",
          ],
        },
        {
          name: "Kurigram",
          upazila: [
            "Bhurungamari",
            "Chilmari",
            "Fulbari",
            "Kurigram-S",
            "Nageswari",
            "Rajarhat",
            "Rajibpur",
            "Rowmari",
            "Ulipur",
          ],
        },
        {
          name: "Lalmonirhat",
          upazila: [
            "Aditmari",
            "Hatibandha",
            "Kaliganj",
            "Lalmonirhat-S",
            "Patgram",
          ],
        },
        {
          name: "Nilphamari",
          upazila: [
            "Dimla",
            "Domar",
            "Jaldhaka",
            "Kishoreganj",
            "Nilphamari-S",
            "Sayedpur",
          ],
        },
        {
          name: "Panchagarh",
          upazila: ["Atwari", "Boda", "Debiganj", "Panchagarh-S", "Tetulia"],
        },
        {
          name: "Rangpur",
          upazila: [
            "Badarganj",
            "Gangachara",
            "Kaunia",
            "Mithapukur",
            "Pirgacha",
            "Pirganj",
            "Rangpur-S",
            "Taraganj",
          ],
        },
        {
          name: "Thakurgaon",
          upazila: [
            "Baliadangi",
            "Haripur",
            "Pirganj",
            "Ranisankail",
            "Thakurgaon-S",
          ],
        },
      ],
    },
    {
      name: "Sylhet",
      district: [
        {
          name: "Habiganj",
          upazila: [
            "Azmiriganj",
            "Bahubal",
            "Baniachong",
            "Chunarughat",
            "Habiganj-S",
            "Lakhai",
            "Madhabpur",
            "Nabiganj",
            "Sayestaganj",
          ],
        },
        {
          name: "Moulvibaza",
          upazila: [
            "Barlekha",
            "Juri",
            "Kamalganj",
            "Kulaura",
            "Moulvibazar-S",
            "Rajnagar",
            "Sreemangal",
          ],
        },
        {
          name: "Sunamganj",
          upazila: [
            "Biswamvarpur",
            "Chatak",
            "Dakhin Sunamganj",
            "Derai",
            "Dharmapasha",
            "Doarabazar",
            "Jagannathpur",
            "Jamalganj",
            "Sulla",
            "Sunamganj-S",
            "Tahirpur",
          ],
        },
        {
          name: "Sylhet",
          upazila: [
            "Balaganj",
            "Beanibazar",
            "Biswanath",
            "Companiganj",
            "Dakshin Surma",
            "Fenchuganj",
            "Golapganj",
            "Gowainghat",
            "Jointiapur",
            "Kanaighat",
            "Osmaninagar",
            "Sylhet-S",
            "Zakiganj",
          ],
        },
      ],
    },
  ],
};
export default Dataset;
